alias gvim='gvim -f'
alias gopen='gnome-open'
alias sublime='/usr/bin/sublime-text'
alias stata='/usr/local/stata13/stata'
alias xstata='/usr/local/stata13/xstata'
alias Rstudio='/usr/lib/rstudio/bin/rstudio'
alias matlab='/usr/local/MATLAB/R2012a/bin/matlab -desktop'
alias ssh_percheron='ssh divenyi@pure.percheron.ceu.edu -p 2222'
alias rmspaces="rename 'y/ /_/' *"
alias R='R --no-save'
alias e='exit'
alias cd..='cd ..'
alias rm=trash
alias inventory='sort | uniq -c | sort -n'
